// GENERATED by design/prototype/gen_dart_tokens.py from design/final_design_tokens.json. DO NOT EDIT.
// ignore_for_file: public_member_api_docs

import 'dart:ui';

class FsPalette {
  const FsPalette({
    required this.tintOpacity, required this.background, required this.surface, required this.surface2, required this.elevated,
    required this.text, required this.text2, required this.textDisabled, required this.onAccent, required this.border,
    required this.borderStrong, required this.accent, required this.accentHover, required this.accentPressed,
    required this.accentText, required this.info, required this.infoText, required this.success, required this.successText,
    required this.warning, required this.warningText, required this.error, required this.errorText, required this.errorSolid,
    required this.neutral, required this.icon, required this.focus, required this.scrim,
  });
  final double tintOpacity;
  final Color background, surface, surface2, elevated, text, text2, textDisabled, onAccent, border, borderStrong;
  final Color accent, accentHover, accentPressed, accentText, info, infoText, success, successText, warning, warningText;
  final Color error, errorText, errorSolid, neutral, icon, focus, scrim;
}

class FsTextSpec {
  const FsTextSpec({required this.size, required this.lineHeight, required this.weight});
  final double size, lineHeight;
  final int weight;
  double get height => lineHeight / size;
}

class FsColors {
  static const dark = FsPalette(
    tintOpacity: 0.16,
    background: Color(0xFF121217),
    surface: Color(0xFF18181F),
    surface2: Color(0xFF1F1F28),
    elevated: Color(0xFF272832),
    text: Color(0xFFE8E9EF),
    text2: Color(0xFFA3A6B4),
    textDisabled: Color(0xFF686B79),
    onAccent: Color(0xFFFFFFFF),
    border: Color(0xFF353744),
    borderStrong: Color(0xFF4B4E60),
    accent: Color(0xFF6C5DF6),
    accentHover: Color(0xFF6152EC),
    accentPressed: Color(0xFF5344D8),
    accentText: Color(0xFFB4ADFF),
    info: Color(0xFF468BFF),
    infoText: Color(0xFF6AA3FF),
    success: Color(0xFF4AC26B),
    successText: Color(0xFF4AC26B),
    warning: Color(0xFFE6B336),
    warningText: Color(0xFFE6B336),
    error: Color(0xFFE14E5F),
    errorText: Color(0xFFF0707F),
    errorSolid: Color(0xFFC4364A),
    neutral: Color(0xFFA3A6B4),
    icon: Color(0xFFB2B5C2),
    focus: Color(0xFF8B80FF),
    scrim: Color(0x9E06060A),
  );
  static const light = FsPalette(
    tintOpacity: 0.1,
    background: Color(0xFFF6F7F9),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFF8F8FB),
    elevated: Color(0xFFFFFFFF),
    text: Color(0xFF282A32),
    text2: Color(0xFF5F6270),
    textDisabled: Color(0xFF8F929D),
    onAccent: Color(0xFFFFFFFF),
    border: Color(0xFFD6D8E0),
    borderStrong: Color(0xFFB7BAC6),
    accent: Color(0xFF6050E2),
    accentHover: Color(0xFF5142D0),
    accentPressed: Color(0xFF4536B8),
    accentText: Color(0xFF4C3FCB),
    info: Color(0xFF377DE9),
    infoText: Color(0xFF1F62CF),
    success: Color(0xFF35A658),
    successText: Color(0xFF1E7A3D),
    warning: Color(0xFFB98207),
    warningText: Color(0xFF8A5F00),
    error: Color(0xFFCB3F4F),
    errorText: Color(0xFFB02B3B),
    errorSolid: Color(0xFFB02B3B),
    neutral: Color(0xFF5F6270),
    icon: Color(0xFF676A76),
    focus: Color(0xFF6050E2),
    scrim: Color(0x6114141E),
  );
}

class FsSpace {
  static const double s2 = 2;
  static const double s4 = 4;
  static const double s6 = 6;
  static const double s8 = 8;
  static const double s12 = 12;
  static const double s16 = 16;
  static const double s20 = 20;
  static const double s24 = 24;
  static const double s32 = 32;
}

class FsRadius {
  static const double small = 8;
  static const double medium = 12;
  static const double large = 20;
  static const double pill = 999;
}

class FsType {
  static const String family = 'Roboto';
  static const caption = FsTextSpec(size: 12, lineHeight: 16, weight: 400);
  static const body = FsTextSpec(size: 15, lineHeight: 22, weight: 400);
  static const title = FsTextSpec(size: 20, lineHeight: 28, weight: 600);
  static const heading = FsTextSpec(size: 28, lineHeight: 36, weight: 600);
}

class FsSize {
  static const double touchTarget = 48;
  static const double buttonHeight = 52;
  static const double appHeaderHeight = 56;
  static const double screenPadding = 20;
  static const double progressHeight = 8;
  static const double iconInline = 20;
  static const double iconHeader = 24;
  static const double iconHero = 40;
  static const double iconShareTile = 44;
  static const double shareTileWidth = 84;
  static const double shareTileHeight = 92;
  static const int shareTileMinColumns = 3;
}

class FsMotion {
  static const Duration fast = Duration(milliseconds: 120);
  static const Duration normal = Duration(milliseconds: 200);
}
