# NON-PRODUCTION DESIGN PROTOTYPE -- not wired into the application.
"""Computes WCAG contrast ratios for the token pairs the designs actually use
and writes design/CONTRAST_AUDIT.md. Exits non-zero if a text pair < 4.5:1
or a graphical pair < 3:1."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
tokens = json.loads((ROOT / "final_design_tokens.json").read_text())


def lum(hexc):
    h = hexc.lstrip("#")
    r, g, b = (int(h[i : i + 2], 16) / 255 for i in (0, 2, 4))
    f = lambda c: c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)


def ratio(a, b):
    la, lb = lum(a), lum(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def blend(fg, bg, a):
    f = [int(fg.lstrip("#")[i : i + 2], 16) for i in (0, 2, 4)]
    b = [int(bg.lstrip("#")[i : i + 2], 16) for i in (0, 2, 4)]
    return "#" + "".join(f"{round(f[i] * a + b[i] * (1 - a)):02X}" for i in range(3))


rows, failed = [], []
for theme, c in tokens["color"].items():
    s, t, st, ac = c["surface"], c["text"], c["status"], c["accent"]
    tint = blend(ac["primary"], s["primary"], ac["tintOpacity"])
    pairs = [
        ("text.primary on surface.background", t["primary"], s["background"], 4.5),
        ("text.primary on surface.primary", t["primary"], s["primary"], 4.5),
        ("text.primary on surface.secondary", t["primary"], s["secondary"], 4.5),
        ("text.primary on surface.elevated", t["primary"], s["elevated"], 4.5),
        ("text.secondary on surface.primary", t["secondary"], s["primary"], 4.5),
        ("text.secondary on surface.background", t["secondary"], s["background"], 4.5),
        ("text.secondary on surface.elevated", t["secondary"], s["elevated"], 4.5),
        ("text.disabled on surface.primary (disabled only, exempt)", t["disabled"], s["primary"], 0),
        ("text.onAccent on accent.primary", t["onAccent"], ac["primary"], 4.5),
        ("text.onAccent on accent.hover", t["onAccent"], ac["hover"], 4.5),
        ("text.onAccent on accent.pressed", t["onAccent"], ac["pressed"], 4.5),
        ("accent.text on selected tint (sidebar selection)", ac["text"], tint, 4.5),
        ("status.infoText on surface.primary", st["infoText"], s["primary"], 4.5),
        ("status.successText on surface.primary", st["successText"], s["primary"], 4.5),
        ("status.warningText on surface.primary", st["warningText"], s["primary"], 4.5),
        ("text.onAccent on status.errorSolid (destructive button)", t["onAccent"], st["errorSolid"], 4.5),
        ("status.errorText on surface.primary", st["errorText"], s["primary"], 4.5),
        ("status.errorText on surface.elevated", st["errorText"], s["elevated"], 4.5),
        ("status.neutral on surface.primary", st["neutral"], s["primary"], 4.5),
        ("border.strong vs surface.primary (graphic)", c["border"]["strong"], s["primary"], 1.5),
        ("status.info fill vs surface.primary (progress)", st["info"], s["primary"], 3.0),
        ("status.success fill vs surface.primary (progress)", st["success"], s["primary"], 3.0),
        ("status.warning fill vs surface.primary (progress)", st["warning"], s["primary"], 3.0),
        ("status.error fill vs surface.primary (progress)", st["error"], s["primary"], 3.0),
        ("focus ring vs surface.primary (graphic)", c["focus"], s["primary"], 3.0),
    ]
    for name, fg, bg, need in pairs:
        r = ratio(fg, bg)
        ok = r >= need
        rows.append((theme, name, fg, bg, r, need, ok))
        if not ok:
            failed.append((theme, name, round(r, 2), need))

lines = ["# Contrast audit (generated by design/prototype/contrast.py)", "",
         "WCAG 2.x relative-luminance ratios for the pairs the final designs use.",
         "Text needs >= 4.5:1; graphical objects (progress fills, focus ring) >= 3:1;",
         "disabled text is exempt by WCAG but is never used for information.", "",
         "| Theme | Pair | Foreground | Background | Ratio | Required | Result |", "|---|---|---|---|---|---|---|"]
for theme, name, fg, bg, r, need, ok in rows:
    req = "exempt" if need == 0 else f"{need}:1"
    lines.append(f"| {theme} | {name} | {fg} | {bg} | {r:.2f}:1 | {req} | {'PASS' if ok else '**FAIL**'} |")
(ROOT / "CONTRAST_AUDIT.md").write_text("\n".join(lines) + "\n")
for f in failed:
    print("FAIL", f)
print(f"{len(rows) - len(failed)}/{len(rows)} pairs pass")
sys.exit(1 if failed else 0)
