"""Generates friendsend/lib/ui/theme/tokens.g.dart from design/final_design_tokens.json (mobile-relevant tokens).

Run: python3 design/prototype/gen_dart_tokens.py [--check]. --check exits 1 when the committed file has drifted.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "design" / "final_design_tokens.json"
OUT = ROOT / "friendsend" / "lib" / "ui" / "theme" / "tokens.g.dart"


def _hex(value: str) -> str:
    return "0xFF" + value.lstrip("#").upper()


def _rgba(value: str) -> str:
    inner = value[value.index("(") + 1 : value.index(")")].split(",")
    r, g, b = (int(x) for x in inner[:3])
    a = round(float(inner[3]) * 255)
    return f"0x{a:02X}{r:02X}{g:02X}{b:02X}"


def _palette(name: str, c: dict) -> str:
    rows = [
        ("background", _hex(c["surface"]["background"])), ("surface", _hex(c["surface"]["primary"])),
        ("surface2", _hex(c["surface"]["secondary"])), ("elevated", _hex(c["surface"]["elevated"])),
        ("text", _hex(c["text"]["primary"])), ("text2", _hex(c["text"]["secondary"])),
        ("textDisabled", _hex(c["text"]["disabled"])), ("onAccent", _hex(c["text"]["onAccent"])),
        ("border", _hex(c["border"]["default"])), ("borderStrong", _hex(c["border"]["strong"])),
        ("accent", _hex(c["accent"]["primary"])), ("accentHover", _hex(c["accent"]["hover"])),
        ("accentPressed", _hex(c["accent"]["pressed"])), ("accentText", _hex(c["accent"]["text"])),
        ("info", _hex(c["status"]["info"])), ("infoText", _hex(c["status"]["infoText"])),
        ("success", _hex(c["status"]["success"])), ("successText", _hex(c["status"]["successText"])),
        ("warning", _hex(c["status"]["warning"])), ("warningText", _hex(c["status"]["warningText"])),
        ("error", _hex(c["status"]["error"])), ("errorText", _hex(c["status"]["errorText"])),
        ("errorSolid", _hex(c["status"]["errorSolid"])), ("neutral", _hex(c["status"]["neutral"])),
        ("icon", _hex(c["icon"]["neutral"])), ("focus", _hex(c["focus"])), ("scrim", _rgba(c["scrim"])),
    ]
    fields = "\n".join(f"    {k}: Color({v})," for k, v in rows)
    return f"  static const {name} = FsPalette(\n    tintOpacity: {c['accent']['tintOpacity']},\n{fields}\n  );"


def render() -> str:
    d = json.loads(SRC.read_text(encoding="utf-8"))
    r, t, s = d["radius"]["mobile"], d["typography"]["mobile"], d["size"]["mobile"]
    typo = "\n".join(
        f"  static const {name} = FsTextSpec(size: {v['size']}, lineHeight: {v['lineHeight']}, weight: {v['weight']});"
        for name, v in t.items()
    )
    spacing = "\n".join(f"  static const double s{k} = {v};" for k, v in d["spacing"].items())
    return f"""// GENERATED by design/prototype/gen_dart_tokens.py from design/final_design_tokens.json. DO NOT EDIT.
// ignore_for_file: public_member_api_docs

import 'dart:ui';

class FsPalette {{
  const FsPalette({{
    required this.tintOpacity, required this.background, required this.surface, required this.surface2, required this.elevated,
    required this.text, required this.text2, required this.textDisabled, required this.onAccent, required this.border,
    required this.borderStrong, required this.accent, required this.accentHover, required this.accentPressed,
    required this.accentText, required this.info, required this.infoText, required this.success, required this.successText,
    required this.warning, required this.warningText, required this.error, required this.errorText, required this.errorSolid,
    required this.neutral, required this.icon, required this.focus, required this.scrim,
  }});
  final double tintOpacity;
  final Color background, surface, surface2, elevated, text, text2, textDisabled, onAccent, border, borderStrong;
  final Color accent, accentHover, accentPressed, accentText, info, infoText, success, successText, warning, warningText;
  final Color error, errorText, errorSolid, neutral, icon, focus, scrim;
}}

class FsTextSpec {{
  const FsTextSpec({{required this.size, required this.lineHeight, required this.weight}});
  final double size, lineHeight;
  final int weight;
  double get height => lineHeight / size;
}}

class FsColors {{
{_palette('dark', d['color']['dark'])}
{_palette('light', d['color']['light'])}
}}

class FsSpace {{
{spacing}
}}

class FsRadius {{
  static const double small = {r['small']};
  static const double medium = {r['medium']};
  static const double large = {r['large']};
  static const double pill = {r['pill']};
}}

class FsType {{
  static const String family = 'Roboto';
{typo}
}}

class FsSize {{
  static const double touchTarget = {s['touchTarget']};
  static const double buttonHeight = {s['buttonHeight']};
  static const double appHeaderHeight = {s['appHeaderHeight']};
  static const double screenPadding = {s['screenPadding']};
  static const double progressHeight = {s['progressHeight']};
  static const double iconInline = {s['icon']['inline']};
  static const double iconHeader = {s['icon']['header']};
  static const double iconHero = {s['icon']['hero']};
  static const double iconShareTile = {s['icon']['shareTile']};
  static const double shareTileWidth = {s['shareTile']['width']};
  static const double shareTileHeight = {s['shareTile']['height']};
  static const int shareTileMinColumns = {s['shareTile']['minColumns']};
}}

class FsMotion {{
  static const Duration fast = Duration(milliseconds: {d['motion']['fast']['ms']});
  static const Duration normal = Duration(milliseconds: {d['motion']['normal']['ms']});
}}
"""


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.read_text(encoding="utf-8") == text else 1)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")
